version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:3:00AM
      interval: "monthly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:3:00AM
      interval: "monthly"
